version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user